### ISSUE TITLE
Nothing shows in browser

### ISSUE THREAD

**Issue by davidmthomsen** [adriangranados/pcap2html#1]
I have Wireshark, I have the pdml2html.xsl file. I run the python script and it creates a .xml file. Opening it in Safari or Chrome is just a blank screen. What am I doing wrong?

**Comment by adriangranados** [comment]
It appears recent security updates to Safari/Chrome block XML files from accessing XSLT files in the same directory. 

There are (ugly) workarounds:

Chrome: https://stackoverflow.com/questions/3828898/can-chrome-be-made-to-perform-an-xsl-transform-on-a-local-file

Safari: https://stackoverflow.com/questions/46478921/can-safari-be-made-to-perform-an-xsl-transform-on-a-local-file

I'm going to change the script to not launch Safari since it won't work unless the browser's settings have been changed as indicated in the link above.

**Comment by adriangranados** [comment]
@davidmthomsen Take a look at the latest changes. Now the conversion is truly done to HTML and you should be able to open the generated HTML file in any browser.
